version: "3.5"

services:
  cassandra:
    image: cassandra:4.1.1
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    expose:
      - "9042"
    networks:
      services-network:
        aliases:
          - cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 30s
      retries: 10

  matching-simulator:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - >
        go test -timeout 180s
        -run ^TestMatchingSimulationSuite$
        -count 1
        -v
        -tags matchingsim
        github.com/uber/cadence/host
        | tee test.log
    environment:
      - "MATCHING_LOG_EVENTS=true"
      - "CASSANDRA_HOST=cassandra"
      - "CASSANDRA=1"
      - "CASSANDRA_SEEDS=cassandra"
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ../../:/cadence
      - /cadence/.build/ # ensure we don't mount the build directory
      - /cadence/.bin/ # ensure we don't mount the bin directory
    networks:
      services-network:
        aliases:
          - integration-test

networks:
  services-network:
    name: services-network
    driver: bridge
